### PR TITLE
[ADD] Support multicall v2

### PR DESCRIPTION
**Pull request by tungnguyen20**
The multicall v2 supported contracts can be found [here](https://github.com/makerdao/multicall)

### CODE REVIEW

**Comment by DarthMike** [comment]
@tungnguyen20 Thanks for the PR! Please address the linting issue by running `[prepareForPush.sh](https://github.com/argentlabs/web3.swift/blob/develop/scripts/prepareForPush.sh)` and also we'll need an integration test against a Goerli contract to be sure it works fine and it won't break with future changes

**Comment by tungnguyen20** [comment]
> @tungnguyen20 Thanks for the PR! Please address the linting issue by running `[prepareForPush.sh](https://github.com/argentlabs/web3.swift/blob/develop/scripts/prepareForPush.sh)` and also we'll need an integration test against a Goerli contract to be sure it works fine and it won't break with future changes

@DarthMike  I just run the script and add test cases. Please help me continue.

**Comment by tungnguyen20** [comment]
@DarthMike I just run the script and add test cases. Please help me continue.

**Comment by DarthMike** [comment]
Some tests will fail (see #311). But we can run anyway for now

**Comment by tungnguyen20** [comment]
Yeah I see :D

**Review by DarthMike — APPROVED** [review]

**Comment by DarthMike** [comment]
@tungnguyen20 You can merge `develop` and tests should pass now

**Comment by tungnguyen20** [comment]
I merged the develop branch. Please help me merge this pull request. Thank you.

**Review by DarthMike — APPROVED** [review]

**Comment by DarthMike** [comment]
@tungnguyen20 strangely this PR is now failing in other tests even though there's nothing changed that would affect it.
I run CI on `develop` and it's passing correctly (https://github.com/argentlabs/web3.swift/actions/runs/4182648660) , trying again

**Comment by tungnguyen20** [comment]
Look likes the private key is missing. Please check it. 
Screen Shot 2023-02-15 at 18 19 09

**Comment by DarthMike** [comment]
Hm I don't understand why, but pulled the changes manually to see if it changes will work in CI
https://github.com/argentlabs/web3.swift/pull/313

**Comment by tungnguyen20** [comment]
Hmm. Don't know why. It passed 😂

**Comment by tungnguyen20** [comment]
I think I will close this PR and reopen a new one which is checked out from latest develop

**Comment by DarthMike** [comment]
@tungnguyen20 you can update from latest develop, I found out why (https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)

**Comment by tungnguyen20** [comment]
@DarthMike Yah I updated. Hope it will help 😁

**Pull request merged**
