### PR TITLE
Replace embedded C library on using shared pod

### PR DESCRIPTION
**Pull request by MortyMerr**
Just to prevent potential conflicts with other web3 libraries which also use secp256k1

### CODE REVIEW

**Comment by MortyMerr** [comment]
Hi @th3m477 could you please check this PR? Thanks :)

**Comment by DarthMike** [comment]
We'll need to make a full diff between current and pod, to be sure there's no difference. Will get back to you when we have bandwidth to check.

**Comment by MortyMerr** [comment]
@DarthMike any updated on that?

**Comment by DarthMike** [comment]
Hi @MortyMerr, I've diffed the code and there's lots of differences. I'll have to dig out which exact version we used when initially developing the library, as it has never been changed. It's possible we need to import another pod, or finally update the library for this.

**Comment by DarthMike** [comment]
@MortyMerr Decided to use https://github.com/Boilertalk/secp256k1.swift, we're doing some testing, we'll merge soon. (See PR #99 )

**Comment by MortyMerr** [comment]
Thanks for updates. Actually  this is even better option 😊

**Pull request closed without merging**
