### PR TITLE
Code Format

### PR DESCRIPTION
**Pull request by dnKaratzas**

### CODE REVIEW

**Review by DarthMike — COMMENTED** [review]
Changes look good, but it would be best at this point to update `Readme.md` 'Contributors' section to explain what needs to be run to abide to code formatting. Maybe add a `format.sh` script so it's easy to call

**Comment by DarthMike** [comment]
Also, better to modify CI to run formatter tool to ensure there's no changes needed before merging

**Comment by dnKaratzas** [comment]
> Also, better to modify CI to run formatter tool to ensure there's no changes needed before merging

Opened an issue for that!

**Comment by DarthMike** [comment]
@dnKaratzas which tool did you use?
[swiftlint](https://github.com/realm/SwiftLint) + [swiftFormat](https://github.com/nicklockwood/SwiftFormat) with default config?

**Comment by dnKaratzas** [comment]
> @dnKaratzas which tool did you use?
> 
> [swiftlint](https://github.com/realm/SwiftLint) + [swiftFormat](https://github.com/nicklockwood/SwiftFormat) with default config?

Swiftlint default rules SwiftFormat I made a configuration and changed some rules I don't like.

**Comment by DarthMike** [comment]
> Swiftlint default rules SwiftFormat I made a configuration and changed some rules I don't like.

@dnKaratzas We'll need to add the rules file to the repo then (`.swiftformat` file)

**Comment by dnKaratzas** [comment]
We will! You could just merge the code format PR and we will work that on the issue I opened

**Review by DarthMike — APPROVED** [review]

**Pull request merged**
